# Generated by Django 5.2.16 on 2026-07-10 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('recruiter_name', models.CharField(blank=True, max_length=200)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('confident', 'Confident'), ('enthusiastic', 'Enthusiastic'), ('fresher-friendly', 'Fresher-Friendly'), ('experienced', 'Experienced')], default='professional', max_length=20)),
                ('document_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('cold_email', 'Cold Email'), ('both', 'Both')], max_length=20)),
                ('cover_letter_content', models.TextField(blank=True, null=True)),
                ('cold_email_content', models.TextField(blank=True, null=True)),
                ('cover_letter_pdf', models.FileField(blank=True, null=True, upload_to='generated_docs/')),
                ('cover_letter_docx', models.FileField(blank=True, null=True, upload_to='generated_docs/')),
                ('cold_email_pdf', models.FileField(blank=True, null=True, upload_to='generated_docs/')),
                ('cold_email_docx', models.FileField(blank=True, null=True, upload_to='generated_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
