# Generated by Django 5.2.15 on 2026-07-08 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_generato', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddocument',
            options={},
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='cold_email_docx',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='cold_email_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='cover_letter_docx',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='cover_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
