# Generated by Django 5.2.15 on 2026-07-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_generato', '0002_alter_generateddocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generated Document', 'verbose_name_plural': 'Generated Documents'},
        ),
    ]
