# Generated by Django 5.2.15 on 2026-07-08 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_generato', '0003_alter_generateddocument_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='resume_text',
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='cold_email_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='cold_email_docx',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='cold_email_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='cover_letter_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='cover_letter_docx',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='cover_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('confident', 'Confident'), ('enthusiastic', 'Enthusiastic'), ('fresher-friendly', 'Fresher-Friendly'), ('experienced', 'Experienced')], default='professional', max_length=20),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
