# Generated by Django 5.2.16 on 2026-07-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(unique=True)),
                ('confidence', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Warning', 'Warning'), ('Deleted', 'Deleted')], default='Safe', max_length=20)),
                ('reasoning', models.TextField()),
                ('warning_sent', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
