# Generated by Django 5.2.16 on 2026-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_hunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghostanalysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Ghost Analysis', 'verbose_name_plural': 'Ghost Analyses'},
        ),
        migrations.AlterField(
            model_name='ghostanalysis',
            name='confidence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ghostanalysis',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
