# Generated by Django 5.2.15 on 2026-07-06 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('Higher Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('PhD', 'PhD')], max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('preferred_job_role', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('0-2 Years', '0-2 Years'), ('2-5 Years', '2-5 Years'), ('5+ Years', '5+ Years')], max_length=20)),
                ('skills', models.TextField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
