# Generated by Django 5.2.15 on 2026-07-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
