# Generated by Django 5.2.15 on 2026-07-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='notify_app_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='notify_job_recs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='notify_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_visible',
            field=models.BooleanField(default=True),
        ),
    ]
