# Generated by Django 5.2.15 on 2026-07-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application_notes_application_status_updated_at_and_more'),
        ('accounts', '0003_application_rejection_reason_and_more'),
        ('accounts', '0003_jobseekerprofile_notify_app_updates_and_more'),
    ]

    operations = [
    ]
