# Generated by Django 5.2.16 on 2026-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260713_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
