# Generated by Django 5.2.15 on 2026-07-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recruiterprofile_total_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
