# Generated by Django 5.2.16 on 2026-07-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_application_status'),
        ('accounts', '0006_recruiterprofile_company_rating_and_more'),
    ]

    operations = [
    ]
