# Generated by Django 5.2.16 on 2026-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='matched_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
