# Generated by Django 5.2.16 on 2026-07-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_application_match_score_application_matched_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_stage',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
