# Generated by Django 5.2.16 on 2026-07-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_application_match_score_application_matched_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='candidate_agent_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
