# Generated by Django 5.2.16 on 2026-07-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_application_last_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_stage',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
