# Generated by Django 5.2.16 on 2026-07-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_invitation_match_score_and_more'),
        ('accounts', '0013_alter_application_status'),
    ]

    operations = [
    ]
