# Generated by Django 5.2.16 on 2026-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20260716_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('0-2 Years', '0-2 Years'), ('2-5 Years', '2-5 Years'), ('5+ Years', '5+ Years')], default='Fresher', max_length=20),
            preserve_default=False,
        ),
    ]
