# Generated by Django 5.2.15 on 2026-07-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_job_scraped_company_name_job_source_job_source_url_and_more'),
        ('accounts', '0015_job_experience_level'),
    ]

    operations = [
    ]
