# Generated by Django 5.2.16 on 2026-07-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewprep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('exited', 'Exited')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=35)),
                ('time_left', models.IntegerField(default=2100)),
                ('score', models.FloatField(default=0.0)),
                ('user_answers', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_test_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'test_id')},
            },
        ),
        migrations.CreateModel(
            name='InterviewPracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('resume_text', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(default='technical', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_practice_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AptitudeDetailedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField(blank=True)),
                ('selected_answer', models.IntegerField(blank=True, null=True)),
                ('correct_answer', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, default='medium', max_length=20)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_answers', to='interviewprep.aptitudetestprogress')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('progress', 'question_id')},
            },
        ),
    ]
