# Generated by Django 5.2.16 on 2026-07-11 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewprep', '0002_aptitudetestprogress_interviewpracticeprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aptitudetestprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aptitudetestprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interviewpracticeprogress',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AptitudeDetailedAnswer',
        ),
        migrations.DeleteModel(
            name='AptitudeTestProgress',
        ),
        migrations.DeleteModel(
            name='InterviewPracticeProgress',
        ),
    ]
